export default [
  'Statues in parks: If the horse has both front legs in the air, the person died in battle; if the horse has one front leg in the air, the person died as a result of wounds received in battle; if the horse has all four legs on the ground, the person died of natural causes.',
  'The expression "to get fired" comes from long ago Clans that wanted to get rid of unwanted people, so they would burn their houses instead of killing them, creating the term "Got fired".',
  '"I am"  is the shortest complete sentence in the English language.',
  'The longest recorded flight of a chicken is thirteen seconds.',
  'The Eisenhower interstate system requires that one mile in every five must be straight in case of war or emergency, they could be used as airstrips.',
  'The name Jeep came from the abbreviation used in the army. G.P. for "General Purpose" vehicle.',
  'The Pentagon, in Arlington, Virginia, has twice as many bathrooms as is necessary, because when it was built in the 1940s, the state of Virginia still had segregation laws requiring separate toilet facilities for blacks and whites.',
  'The cruise liner, Queen Elizabeth II, moves only six inches for each gallon of diesel that it burns.',
  'If you have three quarters, four dimes, and four pennies, you have $1.19, the largest amount of money in coins without being able to make change for a dollar.',
  'In Aspen Colorado, you can have a maximum income of $104,000 and still receive government subsidized housing.',
  'Honking of car horns for a couple that just got married is an old superstition to insure great sex.',
  'The sperm of a mouse is actually longer than the sperm of an elephant.',
  'In medieval France, unfaithful wives were made to chase a chicken through town naked.',
  'The Black Widow spider eats her mate during or after sex.',
  'Eating the heart of a male Partridge was the cure for impotence in ancient Babylon.',
  'A bull can inseminate 300 cows from one single ejaculation.',
  'When a Hawaiian woman wears a flower over her left ear, it means that she is not available.',
  'The "save" icon on Microsoft Word shows a floppy disk with the shutter on backwards.',
  'The following sentence: "A rough-coated, dough-faced, thoughtful ploughman strode through the streets of Scarborough; after falling into a slough, he coughed and hiccoughed." Contains the nine different pronunciations of "ough" in the English Language.',
  'The verb "cleave" is the only English word with two synonyms which are antonyms of each other: adhere and separate.',
  'The only 15-letter word that can be spelled without repeating a letter is uncopyrightable.',
  'The shape of plant collenchyma’s cells and the shape of the bubbles in beer foam are the same - they are orthotetrachidecahedrons.',
  'Emus and kangaroos cannot walk backwards, and are on the Australian coat of arms for that reason.',
  'Cats have over one hundred vocal sounds, while dogs only have about ten.',
  'Blueberry Jelly Bellies were created especially for Ronald Reagan.',
  'PEZ candy even comes in a Coffee flavor.',
  'The first song played on Armed Forces Radio during operation Desert Shield was "Rock the Casba" by the Clash.',
  'Non-dairy creamer is flammable.',
  'The airplane Buddy Holly died in was the "American Pie." (Thus the name of the Don McLean song.)',
  'Each king in a deck of playing cards represents a great king from history. Spades - King David, Clubs - Alexander the Great, Hearts - Charlemagne, and Diamonds - Julius Caesar.',
  'Golf courses cover 4% of North America.',
  'The average person will accidentally eat just under a pound of insects every year.',
  'Until 1994, world maps and globes sold in Albania only had Albania on them.',
  'The value of Pi will be officially "rounded down" to 3.14 from 3.14159265359 on December 31, 1999.',
  'The Great Wall of China is the only man-made structure visible from space.',
  'A piece of paper can be folded no more then 9 times.',
  'The amount of computer Memory required to run WordPerfect for Win95 is 8 times the amount needed aboard the space shuttle.',
  'The average North American will eat 35,000 cookies during their life span.',
  'Between 25% and 33% of the population sneeze when exposed to light.',
  'The most common name in world is Mohammed.',
  'Mount Olympus Mons on Mars is three times the size of Mount Everest.',
  'Most toilets flush in E flat.',
  '2,000 pounds of space dust and other space debris fall on the Earth every day.',
  'Each month, there is at least one report of UFOs from each province of Canada.',
  '40,000 Americans are injured by toilets each year.',
  'You can be fined up to $1,000 for whistling on Sunday in Salt Lake City, Utah.',
  'It takes about 142.18 licks to reach the center of a Tootsie pop.',
  'The serial number of the first MAC ever produced was 2001.',
  'It is illegal to eat oranges while bathing in California.',
  'If done perfectly, a rubix cube combination can be solved in 17 turns.',
  'The average American butt is 14.9 inches long.',
  'More bullets were fired in "Starship Troopers" than any other movie ever made.',
  '60% of electrocutions occur while talking on the telephone during a thunderstorm.',
  'The name of the girl on the statue of liberty is Mother of Exiles.',
  '3.6 cans of Spam are consumed each second.',
  'The buzz from an electric razor in America plays in the key of B flat; Key of G in England.',
  'There are 1,575 steps from the ground floor to the top of the Empire State building.',
  'There are 293 ways to make change for a dollar.',
  'The world record for spitting a watermelon seed is 65 feet 4 inches.',
  'In the Philippine jungle, the yo-yo was first used as a weapon.',
  'Dueling is legal in Paraguay as long as both parties are registered blood donors.',
  'Texas is also the only state that is allowed to fly its state flag at the same height as the U.S. flag.',
  'The three most recognized Western names in China are Jesus Christ, Richard Nixon, & Elvis Presley.',
  'There is a town in Newfoundland, Canada called Dildo.',
  'The Boston University Bridge (on Commonwealth Avenue, Boston, Massachusetts) is the only place in the world where a boat can sail under a train driving under a car driving under an airplane.',
  'All 50 states are listed across the top of the Lincoln Memorial on the back of the $5 bill.',
  'Chewing gum while peeling onions will keep you from crying.',
  'There are more plastic flamingos in the U.S that there are real ones.',
  'The crack of a whip is actually a tiny sonic boom, since the tip breaks the sound barrier.',
  'Jupiter is bigger than all the other planets in our solar system combined.',
  'Hot water is heavier than cold.',
  'The common idea that only 10% of the brain is used it not true as it is impossible to determine the actual percentage because of the complexity of the brain.',
  'Lawn darts are illegal in Canada.',
  'There are more psychoanalysts per capita in Buenos Aires than any other place in the world.',
  'Between 2 and 3 jockeys are killed each year in horse racing.',
  '5,840 people with pillow related injuries checked into U.S. emergency rooms in 1992.',
  'The average woman consumes 6 lbs of lipstick in her lifetime.',
  'Some individuals express concern sharing their soap, rightly so, considering 75% of all people wash from top to bottom.',
  'Conception occurs most in the month of December.',
  'Half of all Americans live within 50 miles of their birthplace.',
  'Honey is the only food which does not spoil.', '3.9% of all women do not wear underwear.',
  'This common everyday occurrence composed of 59% nitrogen, 21% hydrogen, and 9% dioxide is called a "fart".',
  'In 1980, a Las Vegas hospital suspended workers for betting on when patients would die.',
  'Los Angeles full name "El Pueblo de Nuestra Senora la Reina de Los Angeles de Porciuncula" is reduced to 3.63% of its size in the abbreviation "L.A.".',
  'The only real person to ever to appear on a pez dispenser was Betsy Ross.',
  'Only 6 people in the whole world have died from moshing.',
  'The storage capacity of human brain exceeds 4 Terabytes.',
  'In Vermont, the ratio of cows to people is 10:1',
  'Any free-moving liquid in outer space will form itself into a sphere, because of its surface tension.',
  'The average American looks at eight houses before buying one.',
  'In the average lifetime, a person will walk the equivalent of 5 times around the equator.',
  'The first contraceptive was crocodile dung used by the ancient Egyptians.',
  'A signature is called a John Hancock because he signed the Declaration of Independence. Only 2 people signed the declaration of independence on July 4. The Last person signed 2 years later.',
  'Arnold Schonberg suffered from triskaidecaphobia, the fear of the number 13.  He died at 13 minutes from midnight on Friday the 13th.',
  'Weatherman Willard Scott was the first original Ronald McDonald.',
  'Virginia Woolf wrote all her books standing.',
  'Deborah Winger did the voice of E.T.',
  'Kelsey Grammar sings and plays the piano for the theme song of Fraiser.',
  'Thomas Edison, acclaimed inventor of the light bulb, was afraid of the dark.',
  'In England, the Speaker of the House is not allowed to speak.',
  'You can sail all the way around the world at latitude 60 degrees south.',
  'The earth weighs around 6,588,000,000,000,000,000,000,000,000 tons.',
  'Peanuts are one of the ingredients of dynamite.', 'Porcupines can float in water.',
  'A shark is the only fish that can blink with both eyes.',
  'Almonds are a member of the peach family.',
  'February 1865 is the only month in recorded history not to have a full moon.',
  'If the population of China walked past you in single file, the line would never end because of the rate of reproduction.',
  'If you yelled for 8 years, 7 months and 6 days, you will have produced enough sound energy to heat one cup of coffee.',
  'In the last 4000 years, no new animals have been domesticated.',
  'Leonardo Da Vinci invented the scissors.',
  'Nutmeg is extremely poisonous if injected intravenously.',
  'On average, people fear spiders more than they do death.',
  'One of the reasons marijuana is illegal today is because cotton growers in the 1930s lobbied against hemp farmers they saw it as competition.',
  'Shakespeare invented the word "assassination" and "bump".',
  'Some lions mate over 50 times a day.',
  'The ant always falls over on its right side when intoxicated.',
  'The eyes of a donkey are positioned so that it can see all four feet at all times.',
  'Worcestershire sauce in essentially an Anchovy Ketchup.',
  'Rhode Island is the only state which the hammer throw is a legal high school sport.',
  'The average lifespan of an eyelash is five months.', 'A spider has transparent blood.',
  'Every acre of American crops harvested contains 100 pounds of insects.',
  'Prince Charles is an avid collecter of toilet seats.',
  'The most common street name in the U.S. is Second Street.',
  'Tehran is the most expensive city on earth.',
  'The sweat drops drawn in cartoon comic strips are called pleuts.',
  'Babies are most likely to be born on Tuesdays.',
  'The HyperMart outside of Garland Texas has 58 check-outs.',
  'The Minneapolis phone book has 21 pages of Andersons.',
  'Poland is the "stolen car capital of the world".',
];
